### PR TITLE
Support M1/M2 processors 

### PR DESCRIPTION
**Pull request by marodrig**
This work will enable geocat to work with M1/M2 chips.
closes [#250](https://github.com/NCAR/geocat-comp/issues/250)

### CODE REVIEW

**Comment by pilotchute** [comment]
@marodrig this looks good to me, please just change the 3 lines (and trailing newline) that yapf is complaining about and I'll approve.

**Comment by marodrig** [comment]
> @marodrig this looks good to me, please just change the 3 lines (and trailing newline) that yapf is complaining about and I'll approve.

@pilotchute The pre-commit issues is now fixed.

**Review by erogluorhan — APPROVED** [review]
This looks good to me; approved! Just to be sure this is actually working, can you please do either of followings:

- Before getting it merged, pull this branch into local on a M1 platform, build -f2py from that source code, see if `import geocat.comp` works with that installation
- After getting it merged, pull the `main` branch into local on a M1 platform, build -f2py from that source code, see if `import geocat.comp` works with that installation

**Comment by erogluorhan** [comment]
> This looks good to me; approved! Just to be sure this is actually working, can you please do either of followings:
> 
> * Before getting it merged, pull this branch into local on a M1 platform, build -f2py from that source code, see if `import geocat.comp` works with that installation
> * After getting it merged, pull the `main` branch into local on a M1 platform, build -f2py from that source code, see if `import geocat.comp` works with that installation

@marodrig Just ignore the above comment. Instead, I have found [GitHub Actions: Self-hosted runners now support Apple M1 silicon](https://github.com/github/roadmap/issues/507) and committed that addition to this.

**Comment by erogluorhan** [comment]
> @marodrig Just ignore the above comment. Instead, I have found [GitHub Actions: Self-hosted runners now support Apple M1 silicon](https://github.com/github/roadmap/issues/507) and committed that addition to this.

Indeed, ignore this last one: I figured they only support it through self-hosted runners, not through GitHub-hosted runners. We can explore the use of self-hosted runners with GitHub Actions though.

**Pull request merged**
