### PR TITLE
Adding citation information

### PR DESCRIPTION
**Pull request by erogluorhan**
Adds "how to cite" info into README.md and RTD docs.

Also adds `dependabot` as it has been working smoothly with geocat-comp.

### CODE REVIEW

**Comment by michaelavs** [comment]
Just because I saw you added it in with the citation PR in -examples, and saw it while building the f2py environment today, should we add pip dependency to the conda environment with this PR? It doesn't cause the environment build to fail, but it does show a message saying we should have a pip dependency because of (I assume) pre-commit.

**Comment by erogluorhan** [comment]
> Just because I saw you added it in with the citation PR in -examples, and saw it while building the f2py environment today, should we add pip dependency to the conda environment with this PR? It doesn't cause the environment build to fail, but it does show a message saying we should have a pip dependency because of (I assume) pre-commit.

Agreed, done!

**Review by michaelavs — APPROVED** [review]
Looks good to me!

**Review by anissa111 — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
